name: Build and Deploy

on:
  push:
    branches:
      - gitops-upgrade

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }} .
          docker tag ${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }} ${{ secrets.DOCKER_USER }}/spacefolio:latest

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USER }}/spacefolio:latest
  
  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set KUBECONFIG
        run: echo "KUBECONFIG=C:\Users\giris\.kube\proxima-config" >> $env:GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/proximacloud proximacloud-container=${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }}
          kubectl rollout status deployment/proximacloud