name: Build and Deploy on Proxima Cloud

on:
  push:
    branches:
      - gitops-upgrade
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }} .
          docker tag ${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }} ${{ secrets.DOCKER_USER }}/spacefolio:latest

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USER }}/spacefolio:latest
  
  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Set KUBECONFIG
        run: echo "KUBECONFIG=C:\Users\giris\.kube\proxima-config" >> $env:GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          kubectl annotate deployment proximacloud kubernetes.io/change-cause="Deploy image ${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }} (commit ${{ github.sha }})" --overwrite
          
          CURRENT_IMAGE=$(kubectl get deployment proximacloud -o=jsonpath='{.spec.template.spec.containers[0].image}')
          NEW_IMAGE=${{ secrets.DOCKER_USER }}/spacefolio:${{ github.run_number }}

          echo "Current: $CURRENT_IMAGE"
          echo "New: $NEW_IMAGE"

          if [ "$CURRENT_IMAGE" != "$NEW_IMAGE" ]; then
            kubectl set image deployment/proximacloud proximacloud-container=$NEW_IMAGE
            kubectl rollout status deployment/proximacloud
          else
            echo "Image unchanged, skipping deployment"
          fi